version: "3.9"

services:
    rabbitmq:
        image: rabbitmq:4.0-management
        container_name: rabbitmq-myfood
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest 