version: "3.9"

services:

    mysql:
        image: mysql:8.0
        container_name: mysql-myfood
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=myuser
        volumes:
            - ./mysql:/var/lib/mysql

    rabbitmq:
        image: rabbitmq:3.13-management
        container_name: rabbitmq-myfood
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest 
        volumes:
            - ./rabbitmq:/var/lib/rabbitmq/
